// Permission constants for the KBN application
// As described in docs/roles-and-permissions.md

/**
 * Permission constants organized by category
 */
export const PERMISSIONS = {
  // Data Access permissions
  DATA_VIEW: 'DATA_VIEW',
  DATA_EDIT: 'DATA_EDIT',
  DATA_CREATE: 'DATA_CREATE',
  DATA_DELETE: 'DATA_DELETE',
  DATA_EXPORT: 'DATA_EXPORT',
  DATA_IMPORT: 'DATA_IMPORT',

  // User Management permissions
  USER_VIEW: 'USER_VIEW',
  USER_EDIT: 'USER_EDIT',
  USER_CREATE: 'USER_CREATE',
  USER_DELETE: 'USER_DELETE',
  USER_ROLE_EDIT: 'USER_ROLE_EDIT',
  USER_INVITE: 'USER_INVITE',

  // Content Management permissions
  CONTENT_VIEW: 'CONTENT_VIEW',
  CONTENT_EDIT: 'CONTENT_EDIT',
  CONTENT_CREATE: 'CONTENT_CREATE',
  CONTENT_DELETE: 'CONTENT_DELETE',
  CONTENT_PUBLISH: 'CONTENT_PUBLISH',

  // System Configuration permissions
  SYSTEM_SETTINGS_VIEW: 'SYSTEM_SETTINGS_VIEW',
  SYSTEM_SETTINGS_EDIT: 'SYSTEM_SETTINGS_EDIT',
  SYSTEM_LOGS_VIEW: 'SYSTEM_LOGS_VIEW',

  // Operational Actions permissions
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_CREATE: 'REPORT_CREATE',
  TASK_ASSIGN: 'TASK_ASSIGN',
  TASK_COMPLETE: 'TASK_COMPLETE',

  // Document Workflow permissions
  DOCUMENT_CREATE: 'DOCUMENT_CREATE',
  DOCUMENT_EDIT: 'DOCUMENT_EDIT',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  DOCUMENT_DELETE: 'DOCUMENT_DELETE',
  DOCUMENT_REVIEW: 'DOCUMENT_REVIEW',
  DOCUMENT_APPROVE: 'DOCUMENT_APPROVE',
  DOCUMENT_REJECT: 'DOCUMENT_REJECT',

  // Region Management permissions
  BRANCH_MANAGE: 'BRANCH_MANAGE',
  BRANCH_REPORTS_VIEW: 'BRANCH_REPORTS_VIEW',
  BRANCH_ANALYTICS_VIEW: 'BRANCH_ANALYTICS_VIEW',
  PROVINCE_MANAGE: 'PROVINCE_MANAGE',
  PROVINCE_REPORTS_VIEW: 'PROVINCE_REPORTS_VIEW',
  PROVINCE_ANALYTICS_VIEW: 'PROVINCE_ANALYTICS_VIEW'
} as const;

// Create a type for the permission values
export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Permission categories for organization
export const PERMISSION_CATEGORIES: Record<string, Permission[]> = {
  DATA_ACCESS: [
    PERMISSIONS.DATA_VIEW,
    PERMISSIONS.DATA_EDIT,
    PERMISSIONS.DATA_CREATE,
    PERMISSIONS.DATA_DELETE,
    PERMISSIONS.DATA_EXPORT,
    PERMISSIONS.DATA_IMPORT
  ],
  USER_MANAGEMENT: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_ROLE_EDIT,
    PERMISSIONS.USER_INVITE
  ],
  CONTENT_MANAGEMENT: [
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_EDIT,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_DELETE,
    PERMISSIONS.CONTENT_PUBLISH
  ],
  SYSTEM_CONFIGURATION: [
    PERMISSIONS.SYSTEM_SETTINGS_VIEW,
    PERMISSIONS.SYSTEM_SETTINGS_EDIT,
    PERMISSIONS.SYSTEM_LOGS_VIEW
  ],
  OPERATIONAL_ACTIONS: [
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_COMPLETE
  ],
  DOCUMENT_WORKFLOW: [
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_EDIT,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.DOCUMENT_REVIEW,
    PERMISSIONS.DOCUMENT_APPROVE,
    PERMISSIONS.DOCUMENT_REJECT
  ],
  REGION_MANAGEMENT: [
    PERMISSIONS.BRANCH_MANAGE,
    PERMISSIONS.BRANCH_REPORTS_VIEW,
    PERMISSIONS.BRANCH_ANALYTICS_VIEW,
    PERMISSIONS.PROVINCE_MANAGE,
    PERMISSIONS.PROVINCE_REPORTS_VIEW,
    PERMISSIONS.PROVINCE_ANALYTICS_VIEW
  ]
};
