// Permission constants for the KBN application
// As described in docs/roles-and-permissions.md

/**
 * Permission constants organized by category
 */
export const PERMISSIONS = {
  // Data Access permissions
  DATA_VIEW: 'DATA_VIEW',
  DATA_EDIT: 'DATA_EDIT',
  DATA_CREATE: 'DATA_CREATE',
  DATA_DELETE: 'DATA_DELETE',
  DATA_EXPORT: 'DATA_EXPORT',
  DATA_IMPORT: 'DATA_IMPORT',

  // User Management permissions
  USER_VIEW: 'USER_VIEW',
  USER_EDIT: 'USER_EDIT',
  USER_CREATE: 'USER_CREATE',
  USER_DELETE: 'USER_DELETE',
  USER_ROLE_EDIT: 'USER_ROLE_EDIT',
  USER_INVITE: 'USER_INVITE',

  // Content Management permissions
  CONTENT_VIEW: 'CONTENT_VIEW',
  CONTENT_EDIT: 'CONTENT_EDIT',
  CONTENT_CREATE: 'CONTENT_CREATE',
  CONTENT_DELETE: 'CONTENT_DELETE',
  CONTENT_PUBLISH: 'CONTENT_PUBLISH',

  // System Configuration permissions
  SYSTEM_SETTINGS_VIEW: 'SYSTEM_SETTINGS_VIEW',
  SYSTEM_SETTINGS_EDIT: 'SYSTEM_SETTINGS_EDIT',
  SYSTEM_LOGS_VIEW: 'SYSTEM_LOGS_VIEW',

  // Operational Actions permissions
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_CREATE: 'REPORT_CREATE',
  TASK_ASSIGN: 'TASK_ASSIGN',
  TASK_COMPLETE: 'TASK_COMPLETE',

  // Document Workflow permissions
  DOCUMENT_CREATE: 'DOCUMENT_CREATE',
  DOCUMENT_EDIT: 'DOCUMENT_EDIT',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  DOCUMENT_DELETE: 'DOCUMENT_DELETE',
  DOCUMENT_REVIEW: 'DOCUMENT_REVIEW',
  DOCUMENT_APPROVE: 'DOCUMENT_APPROVE',
  DOCUMENT_REJECT: 'DOCUMENT_REJECT',

  // Region Management permissions
  BRANCH_MANAGE: 'BRANCH_MANAGE',
  BRANCH_REPORTS_VIEW: 'BRANCH_REPORTS_VIEW',
  BRANCH_ANALYTICS_VIEW: 'BRANCH_ANALYTICS_VIEW',
  PROVINCE_MANAGE: 'PROVINCE_MANAGE',
  PROVINCE_REPORTS_VIEW: 'PROVINCE_REPORTS_VIEW',
  PROVINCE_ANALYTICS_VIEW: 'PROVINCE_ANALYTICS_VIEW',

  // Account permissions
  VIEW_ACCOUNTS: 'VIEW_ACCOUNTS',
  MANAGE_ACCOUNTS: 'MANAGE_ACCOUNTS',
  VIEW_INCOME: 'VIEW_INCOME',
  MANAGE_INCOME: 'MANAGE_INCOME',
  VIEW_EXPENSE: 'VIEW_EXPENSE',
  MANAGE_EXPENSE: 'MANAGE_EXPENSE',
  VIEW_REPORTS: 'VIEW_REPORTS',
  MANAGE_REPORTS: 'MANAGE_REPORTS',
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_USERS: 'VIEW_USERS',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_ROLES: 'VIEW_ROLES',
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_PROVINCES: 'VIEW_PROVINCES',
  MANAGE_PROVINCES: 'MANAGE_PROVINCES'
} as const;

// Create a type for the permission values
export type Permission = keyof typeof PERMISSIONS;

export const PERMISSION_CATEGORIES: Record<string, Permission[]> = {
  DATA_ACCESS: [
    'DATA_VIEW',
    'DATA_EDIT',
    'DATA_CREATE',
    'DATA_DELETE',
    'DATA_EXPORT',
    'DATA_IMPORT'
  ],
  USER_MANAGEMENT: [
    'USER_VIEW',
    'USER_EDIT',
    'USER_CREATE',
    'USER_DELETE',
    'USER_ROLE_EDIT',
    'USER_INVITE'
  ],
  CONTENT_MANAGEMENT: [
    'CONTENT_VIEW',
    'CONTENT_EDIT',
    'CONTENT_CREATE',
    'CONTENT_DELETE',
    'CONTENT_PUBLISH'
  ],
  SYSTEM_CONFIGURATION: [
    'SYSTEM_SETTINGS_VIEW',
    'SYSTEM_SETTINGS_EDIT',
    'SYSTEM_LOGS_VIEW'
  ],
  OPERATIONAL_ACTIONS: [
    'REPORT_VIEW',
    'REPORT_CREATE',
    'TASK_ASSIGN',
    'TASK_COMPLETE'
  ],
  DOCUMENT_WORKFLOW: [
    'DOCUMENT_VIEW',
    'DOCUMENT_CREATE',
    'DOCUMENT_EDIT',
    'DOCUMENT_DELETE',
    'DOCUMENT_REVIEW',
    'DOCUMENT_APPROVE',
    'DOCUMENT_REJECT'
  ],
  REGION_MANAGEMENT: [
    'BRANCH_MANAGE',
    'BRANCH_REPORTS_VIEW',
    'BRANCH_ANALYTICS_VIEW',
    'PROVINCE_MANAGE',
    'PROVINCE_REPORTS_VIEW',
    'PROVINCE_ANALYTICS_VIEW'
  ],
  ACCOUNT_MANAGEMENT: [
    'VIEW_ACCOUNTS',
    'MANAGE_ACCOUNTS',
    'VIEW_INCOME',
    'MANAGE_INCOME',
    'VIEW_EXPENSE',
    'MANAGE_EXPENSE',
    'VIEW_REPORTS',
    'MANAGE_REPORTS',
    'VIEW_SETTINGS',
    'MANAGE_SETTINGS',
    'VIEW_USERS',
    'MANAGE_USERS',
    'VIEW_ROLES',
    'MANAGE_ROLES',
    'VIEW_PROVINCES',
    'MANAGE_PROVINCES'
  ]
};

/**
 * Type for permission keys
 */
export type PermissionKey = keyof typeof PERMISSIONS;

/**
 * Type for permission values
 */
export type PermissionValue = typeof PERMISSIONS[PermissionKey];
